ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_status_check;

ALTER TABLE jobs ADD CONSTRAINT jobs_status_check
  CHECK (status IN ('QUEUED', 'CLAIMED', 'PRINTING', 'COMPLETED', 'FAILED', 'FAILED_PERMANENT', 'CANCELLED'));
